declare module "typings" {
  import type * as Lib from "lib";
  import type * as PixiJS from "pixi.js";

  export declare var PIXI: typeof PixiJS;
  export declare var app: Lib.App;
  export declare var App: typeof Lib.App;
  export declare var Layer: typeof Lib.Layer;

  export declare var Protocol: {
    CONNECT: "connection";
    CONNECTED: "onconnected";
    DISCONNECT: "disconnect";
    DISCONNECTED: "ondisconnected";
    ECHO: "a";
    ECHO_RESP: "b";
    INFO: "c";
    SESSION: "d";
    Session: {
      REGISTER: "e";
      CREATE: "f";
      CREATE_RESP: "g";
      JOIN_MODE: "h";
      JOIN_RESP: "i";
      JOIN_GAME: "j";
      LEAVE: "k";
      LEAVE_RESP: "l";
      LIST_GAMES: "m";
      LIST_GAMES_RESP: "n";
      CLIENT_AUTH: "o1";
    };
    GAME: "p";
    GAME_BIN: "q";
    Game: {
      UPDATE: "r";
      REQ: "t";
      INPUT: "v";
      INFO: "w";
      MESSAGE: "x";
      COMMAND: "y";
      ACTION: "z";
      STATUS: "aa";
      TRIGGER_RESPAWN: "ab";
    };
    SIGNAL_FULL: "ad";
  };

  type Font = PixiJS.TextStyle;
  export declare var FontStyle: {
    LargeDefault: Font;
    MediumBlack: Font;
    LeaderboardColumn: Font;
    LeaderboardData: Font;
    LeaderboardFieldTitle: Font;
    SmallMenuTextOrange: Font;
    SmallMenuTextWhite: Font;
    SmallMenuTextOrange2: Font;
    LeaderboardPointText: Font;
    MediumOrangeText: Font;
    SmallRankingTextOrange: Font;
    SmallClanBrowserText: Font;
    SmallMenuTextOrange3: Font;
    SmallMenuTextOrange4: Font;
    SmallMenuTextWhite2: Font;
    MediumMenuTextOrange: Font;
    ServerListTitle: Font;
    MenuTitle: Font;
    SmallMenuTextYellow: Font;
    SmallLabelText: Font;
    MediumMenuTextOrange2: Font;
    SmallLabelText2: Font;
    SmallMenuTextOrange5: Font;
    LeaderboardOptionsText: Font;
    DropdownItemText: Font;
    ButtonTitle: Font;
    ChatMessage: Font;
    MenuData1: Font;
    InputFieldTitle1: Font;
    ActivityText: Font;
    CreatedText: Font;
    OverviewTitle: Font;
    LeaderboardTitle: Font;
    WeaponMenuTitle: Font;
    InputText: Font;
    CustomizationItemTextSmall: Font;
    SmallLabelText3: Font;
    VSText: Font;
    VSLoadingText: Font;
    VSRulesText: Font;
    VSRulesTextItalic: Font;
    VSRulesDescText: Font;
    VSStartingText: Font;
    VSPlayerLabelText: Font;
    VSCounterText: Font;
    ReadyBarText: Font;
    HudTitleBarText: Font;
    HudMediumTextWhite: Font;
    SmallLabelText4: Font;
    HudMediumTextWhite2: Font;
    HudComboText: Font;
    ConsoleText: Font;
    ActionTableText: Font;
    AmmoBarText: Font;
    InputFieldText: Font;
    WeaponItem: Font;
    ChatBubbleText: Font;
    SocialDropdownText: Font;
    SocialMenuItem: Font;
    RankingItem: Font;
    ProfileTabText: Font;
    CustomizationItem: Font;
    ClanTitle: Font;
    PVPResultTitle: Font;
    PVPResultTitle2: Font;
    PVPResultData: Font;
    PVPResultDataRank: Font;
    PVPResultDataPromo: Font;
    PVPVSTitle: Font;
    GameoverCountdown: Font;
  };
}
