export const NinjaMaps = {
  "1": "Hull",
  "2": "Igloo",
  "3": "Temple",
  "4": "DragonsDen",
  "5": "dm_Arena1",
  "6": "Elysium",
  "7": "Tobruk",
  "8": "ColdFusion",
  "9": "Twin Faces",
  "10": "KodysIsland",
  "11": "Canyon",
  "12": "Hill364",
  "13": "Stasis",
  "14": "ctf_Evening",
  "15": "ArcticDusk",
  "16": "Cathedral",
  "17": "ctf_Lambda",
  "18": "Aerial",
  "19": "ctf_FacingWorlds",
  "20": "ctf_Ash",
  "21": "ctf_Naom",
  "22": "dm_Hunter",
  "23": "Tribal",
  "24": "Kiwi",
  "26": "Webb",
  "27": "dm_Sleet",
  "28": "SpaceStation",
  "29": "Sinkhole",
  "30": "LonelyIsland",
  "31": "dm_Nexus",
};
